version: '3.8'

volumes:
  test_volume:

services:
  redis:
    container_name: local-redis
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql
    container_name: local-mysql
    volumes:
      - test_volume:/var/lib/data
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=ticket-booking
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
