spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/test_db
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    hibernate:
      ddl-auto: create

  config:
    import:
      - "optional:secrets.yml"
