spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/test_db
    username: sa
    password:
    hikari:
      pool-name: testHikari
      maximum-pool-size: 10

  h2:
    console:
      enabled: true
      path: /h2-console

  config:
    import:
      - "optional:secrets.yml"

